version: "3"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=MINIO_SECRET_KEY
    volumes:
      - "./.minio/data:/export"
      - "./.minio/config:/root/.minio"
    command: server --console-address ":9001" /export
    networks:
      - hero-network
volumes:
  hero-mysql: