version: "3"

services:
  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    container_name: hero-apache
    volumes:
      - ./src:/var/www:cached
    working_dir: /var/www
    restart: unless-stopped
    ports:
      - ${APACHE_PORT}:80
      - ${ECHO_PORT}:6001
    environment:
      - SERVICE_NAME=apache
      - SERVICE_TAGS=dev
    networks:
      - hero-network
  mysql:
    image: mysql:8.0
    container_name: hero-mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - hero-mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=sOQSO6DxD
      - MYSQL_DATABASE=hero
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    networks:
      - hero-network
  redis:
    image: redis:alpine
    container_name: hero-redis
    ports:
        - ${REDIS_PORT}:6379
    volumes:
        - hero-cache:/data
    networks:
      - hero-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hero-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=sOQSO6DxD
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    networks:
      - hero-network
  mail:
    image: mailhog/mailhog
    container_name: hero-mail
    ports:
      - ${MAILHOG_PORT}:8025
    networks:
      - hero-network
networks:
  hero-network:
    driver: bridge
volumes:
  hero-mysql:
  hero-cache:
