/**
 * NEO Accordions enums
 */

const Accordions = {
  ORGANIZATION_NAME: 1,
  LOCATION: 2,
  SELF_INTRODUCTION: 3,
  HISTORY_ESTABLISHMENT: 4,
  EMAIL_ADDRESS: 5,
  TELEPHONE: 6,
  URL: 7,
  INDUSTRY: 8,
  BUSINESS_HOLIDAY_INFO: 9,
  QUALIFICATIONS_SKILLS: 10,
  AWARD_HISTORY: 11,
  PROFILE_VIDEO: 12,
  PRODUCT: 13,
  OVERSEAS: 14,
};

export default Accordions;
