<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Document;
use DB;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Truncate Storage Type
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('documents')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Insert pre-defined attributes
        Document::insert([
            [//1
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'document_1.png',
                'mime_type' => 'image/png',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/1/1_document_1.png',
                'file_bytes' => 1024,
            ],
            [//2
                'owner_rio_id' => null,
                'owner_neo_id' => 1,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'document_2.jpg',
                'mime_type' => 'image/jpeg',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/neo/1/2_document_2.jpg',
                'file_bytes' => 1024,
            ],
            [//3
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'document_3.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/1/3_document_3.pdf',
                'file_bytes' => 1024,
            ],
            [//4
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 1,
                'document_name' => 'Folder_1',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//5
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => 4,
                'document_type' => 2,
                'document_name' => 'sub_document_1.png',
                'mime_type' => 'image/png',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/1/5_sub_document_1.png',
                'file_bytes' => 1024,
            ],
            [//6
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => 4,
                'document_type' => 2,
                'document_name' => 'sub_document_2.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/1/6_sub_document_2.pdf',
                'file_bytes' => 1024,
            ],
            [//7
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => 4,
                'document_type' => 1,
                'document_name' => 'Folder_Subfolder_1',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//8
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => 7,
                'document_type' => 2,
                'document_name' => 'sub_sub_document_1.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/1/8_sub_sub_document_1.pdf',
                'file_bytes' => 1024,
            ],
            [//9
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => 4,
                'document_type' => 2,
                'document_name' => 'sub_document_3.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/1/9_sub_document_3.pdf',
                'file_bytes' => 1024,
            ],
            [//10
                'owner_rio_id' => null,
                'owner_neo_id' => 1,
                'directory_id' => null,
                'document_type' => 1,
                'document_name' => 'Neo_Folder_1',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//11
                'owner_rio_id' => null,
                'owner_neo_id' => 1,
                'directory_id' => 10,
                'document_type' => 2,
                'document_name' => 'sub_neo_document_1.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/neo/1/11_sub_neo_document_1.pdf',
                'file_bytes' => 1024,
            ],
            [//12
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'document2_1.png',
                'mime_type' => 'image/png',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/2/12_document2_1.png',
                'file_bytes' => 1024,
            ],
            [//13
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'document2_2.jpg',
                'mime_type' => 'image/jepg',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/2/13_document2_2.jpg',
                'file_bytes' => 1024,
            ],
            [//14
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'document2_3.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/2/14_document2_3.pdf',
                'file_bytes' => 1024,
            ],
            [//15
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 1,
                'document_name' => 'Folder2_1',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//16
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 1,
                'document_name' => 'Folder2_2',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//17
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => 16,
                'document_type' => 1,
                'document_name' => 'Folder2_subfolder_1',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//18
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => 16,
                'document_type' => 2,
                'document_name' => 'Folder2_document_1.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/2/18_Folder2_document_1.pdf',
                'file_bytes' => 1024,
            ],
            [//19
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => 16,
                'document_type' => 2,
                'document_name' => 'Folder2_document_2.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/2/19_Folder2_document_2.pdf',
                'file_bytes' => 1024,
            ],
            [//20
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'directory_id' => 16,
                'document_type' => 2,
                'document_name' => 'Folder2_document_3.jpg',
                'mime_type' => 'image/jepg',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/rio/2/20_Folder2_document_3.jpg',
                'file_bytes' => 1024,
            ],
            [//21
                'owner_rio_id' => null,
                'owner_neo_id' => 3,
                'directory_id' => null,
                'document_type' => 1,
                'document_name' => 'Neo_Folder2_1',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//22
                'owner_rio_id' => null,
                'owner_neo_id' => 3,
                'directory_id' => null,
                'document_type' => 1,
                'document_name' => 'Neo_Folder2_2',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
            [//23
                'owner_rio_id' => null,
                'owner_neo_id' => 3,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'Neo_document2_1.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/neo/3/23_Neo_document2_1.pdf',
                'file_bytes' => 1024,
            ],
            [//24
                'owner_rio_id' => null,
                'owner_neo_id' => 3,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'Neo_document2_2.pdf',
                'mime_type' => 'application/pdf',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/neo/3/24_Neo_document2_2.pdf',
                'file_bytes' => 1024,
            ],
            [//25
                'owner_rio_id' => null,
                'owner_neo_id' => 3,
                'directory_id' => null,
                'document_type' => 2,
                'document_name' => 'Neo_document2_3.jpg',
                'mime_type' => 'image/jepg',
                'storage_type_id' => 1,
                'storage_path' => 'private/documents/neo/3/25_Neo_document2_3.jpg',
                'file_bytes' => 1024,
            ],
            [//26
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'directory_id' => null,
                'document_type' => 1,
                'document_name' => 'Folder_1 2nd',
                'mime_type' => null,
                'storage_type_id' => 1,
                'storage_path' => null,
                'file_bytes' => null,
            ],
        ]);
    }
}
