<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Knowledge;
use DB;

class KnowledgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Truncate table
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('knowledges')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Insert data
        Knowledge::insert([
            [
                'id' => 1,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 1',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-12 09:55:36',
                'updated_at' => '2022-07-12 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 2',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-12 09:55:36',
                'updated_at' => '2022-07-12 09:55:36',
                'deleted_at' => '2022-07-14 09:55:36',
            ],
            [
                'id' => 3,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => 4,
                'type' => 2,
                'task_title' => 'Article 3',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-12 09:55:36',
                'updated_at' => '2022-07-12 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 1',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-13 09:55:36',
                'updated_at' => '2022-07-13 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'created_rio_id' => 2,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 2',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-13 09:55:36',
                'updated_at' => '2022-07-13 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'created_rio_id' => 2,
                'directory_id' => 5,
                'type' => 2,
                'task_title' => 'Article 4',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-13 09:55:36',
                'updated_at' => '2022-07-13 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'owner_rio_id' => 3,
                'owner_neo_id' => null,
                'created_rio_id' => 3,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 5',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-14 00:00:50',
                'updated_at' => '2022-07-14 00:00:50',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'owner_rio_id' => 3,
                'owner_neo_id' => null,
                'created_rio_id' => 3,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 6',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-14 09:55:36',
                'updated_at' => '2022-07-14 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'owner_rio_id' => null,
                'owner_neo_id' => 1,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 7',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-14 09:55:36',
                'updated_at' => '2022-07-14 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'owner_rio_id' => null,
                'owner_neo_id' => 1,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 8',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-14 09:55:36',
                'updated_at' => '2022-07-14 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'owner_rio_id' => null,
                'owner_neo_id' => 2,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 9',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 1,
                'created_at' => '2022-07-14 09:55:36',
                'updated_at' => '2022-07-14 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'owner_rio_id' => null,
                'owner_neo_id' => 2,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 2,
                'task_title' => 'Article 10',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 1,
                'created_at' => '2022-07-14 09:55:36',
                'updated_at' => '2022-07-14 09:55:36',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 3',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 10:00:10',
                'updated_at' => '2022-07-14 10:00:10',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 4',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 10:00:10',
                'updated_at' => '2022-07-14 10:00:10',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => 13,
                'type' => 2,
                'task_title' => 'Article 11',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-14 10:00:10',
                'updated_at' => '2022-07-14 10:00:10',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => 13,
                'type' => 2,
                'task_title' => 'Article 12',
                'contents' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'urls' => null,
                'is_draft' => 0,
                'created_at' => '2022-07-14 10:00:10',
                'updated_at' => '2022-07-14 10:00:10',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'created_rio_id' => 2,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 5',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 10:02:52',
                'updated_at' => '2022-07-14 10:02:52',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'created_rio_id' => 2,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 6',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 10:02:52',
                'updated_at' => '2022-07-14 10:02:52',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'owner_rio_id' => 2,
                'owner_neo_id' => null,
                'created_rio_id' => 2,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 7',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 10:02:52',
                'updated_at' => '2022-07-14 10:02:52',
                'deleted_at' => '2022-07-14 11:02:52',
            ],
            [
                'id' => 20,
                'owner_rio_id' => 3,
                'owner_neo_id' => null,
                'created_rio_id' => 3,
                'directory_id' => null,
                'type' => 1,
                'task_title' => 'Folder 8',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 10:02:52',
                'updated_at' => '2022-07-14 10:02:52',
                'deleted_at' => '2022-07-14 11:02:52',
            ],
            [
                'id' => 21,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => 4,
                'type' => 1,
                'task_title' => 'Folder 9 within Folder 1',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 14:56:43',
                'updated_at' => '2022-07-14 14:56:43',
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'owner_rio_id' => 1,
                'owner_neo_id' => null,
                'created_rio_id' => 1,
                'directory_id' => 4,
                'type' => 1,
                'task_title' => 'Folder 10 within Folder 1',
                'contents' => null,
                'urls' => null,
                'is_draft' => null,
                'created_at' => '2022-07-14 14:57:03',
                'updated_at' => '2022-07-14 14:57:03',
                'deleted_at' => null,
            ],
        ]);
    }
}
